#!/usr/bin/python3

import struct
import json
import sys
import os
from imp import load_source

filename = sys.argv[3] + sys.argv[4]
icon_to_repl = sys.argv[2]
icon_for_repl = sys.argv[1]
absolute_path = os.path.split(os.path.abspath(__file__))[0] + "/"
data_pack = load_source('data_pack', absolute_path + 'data_pack.py')
svgtopng = load_source('svgtopng', absolute_path + 'svgtopng.py')


filename_svg, file_extension = os.path.splitext(icon_for_repl)
if file_extension == '.svg':
    pngbytes = svgtopng.convert_svg2bin(icon_for_repl)
else:
    with open(icon_for_repl, 'rb') as pngfile:
        pngbytes = pngfile.read()

dataPack = data_pack.ReadDataPack(filename)
dataPack.resources[int(icon_to_repl)] = pngbytes
try:
    data_pack.WriteDataPack(dataPack.resources, filename, 0)
except TypeError:
    exit()
