#!/usr/bin/python3
from os import path, makedirs
import sys

hexchat_path = sys.argv[1]


app_path = hexchat_path.strip("/").split("/")
icons_dir = app_path[len(app_path) - 1]
del app_path[len(app_path) - 1]
app_path = "/" + "/".join(app_path) + "/"
if path.exists(app_path):
    if not path.isdir(app_path + icons_dir + "/"):
        makedirs(app_path + icons_dir + "/", exist_ok=True)
        mchown(app_path + icons_dir + "/")
