#!/usr/bin/python3

import sys
from os import symlink, chown, getenv
from subprocess import call

origfile = sys.argv[1]
symlfile = sys.argv[3] + "/" + sys.argv[2]

if len(sys.argv) <= 4:
	if origfile.endswith(".svg"):
        call(["svg2png.py", origfile, symlfile], stdout=PIPE, stderr=PIPE)
	    chown(symlfile, int(getenv('SUDO_UID')), int(getenv('SUDO_GID'))) 
	else:
	    symlink(origfile, symlfile)
else:
	symlink(sys.argv[3] + "/" + sys.argv[4], symlfile)
