#!/usr/bin/python3

import sys
from os import symlink, chown, getenv, remove
from subprocess import Popen, PIPE
from imp import load_source

svgtopng = load_source('svgtopng', './database/scripts/svgtopng.py')

origfile = sys.argv[1]
symlfile = sys.argv[3] + sys.argv[2]

if origfile.endswith(".svg"):
    svgtopng.convert_svg2png(origfile, symlfile)
    chown(symlfile, int(getenv("SUDO_UID")), int(getenv("SUDO_GID")))
else:
    try:
        remove(symlfile)
        symlink(origfile, symlfile)
    except FileNotFoundError:
        symlink(origfile, symlfile)
