#!/bin/bash
cd ./database/scripts/

if [ "$4" -eq 0 ]; then
    rm -f resources_old.zip
    rm -rf resources_old 
    cp $3/resources.zip resources_old.zip
    unzip resources_old.zip -d resources_old/
fi

if [[ $1 == *.svg ]]; then
    python3 svgtopng.py $1 resources_old/_linux/$2
else
    cp $1 resources_old/_linux/$2
fi

if [ "$4" -eq -1 ]; then
    cd resources_old/
    zip -r resources_patched.zip .
    mv resources_patched.zip $3/resources.zip
    cd ./..
    rm -f resources_old.zip
    rm -rf resources_old 
fi
